### ISSUE TITLE
Is this repo being updated, is it accepting PR?

### ISSUE THREAD

**Issue by datatalking** [aneesahmed777/SignalFlowGraph-GainSolver#1]
I've enjoyed reading through the code and wanted to look at using this in a testing environment this summer but its been five years and I wasn't sure if it was solely for research or if it could be used in testing then production environment ready.

**Comment by aneesahmedpro** [comment]
I'm so honoured that someone found this project useful! 😊

To answer the question: No, this is not an active project anymore. Unfortunately, I don't have the time to even accept PRs 😅.

I encourage you to fork this repo and modify that as you please 👍.

Feel free to reach out to me personally if you have any questions, I'll try to reply.
